all: build run

build:
	docker build -t leg12dof:gpu .

run:
	xhost +local:docker
	docker run -it --rm \
		--net=host \
		--device=/dev/ttyUSB0 \
		--env DISPLAY=$DISPLAY \
		--env QT_X11_NO_MITSHM=1 \
		--volume /tmp/.X11-unix:/tmp/.X11-unix \
		--volume ../:/odri \
		--privileged \
		leg12dof:gpu
